[2017-04-07 14:42:30]: 

[2017-04-07 14:42:45]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\spiders\ProcessDayUrlSpider.py", line 34, in parse
    for number in range(1, page_numer + 1, 1):
TypeError: coercing to Unicode: need string or buffer, int found
 coercing to Unicode: need string or buffer, int found
[2017-04-07 14:42:45]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\database\ServerHandler.py", line 25, in add_message
    channel.queue_declare(queue=queue, durable=queue_durable)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 2329, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 1181, in _flush_output
    raise exceptions.ChannelClosed(method.reply_code, method.reply_text)
ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue '2016_day_url_queue' in vhost '/': received 'true' but current is 'false'")
 
[2017-04-07 14:45:00]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\spiders\ProcessDayUrlSpider.py", line 34, in parse
    for number in range(1, page_numer + 1, 1):
TypeError: coercing to Unicode: need string or buffer, int found
 coercing to Unicode: need string or buffer, int found
[2017-04-07 14:45:00]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\database\ServerHandler.py", line 25, in add_message
    channel.queue_declare(queue=queue, durable=queue_durable)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 2329, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 1181, in _flush_output
    raise exceptions.ChannelClosed(method.reply_code, method.reply_text)
ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue '2016_day_url_queue' in vhost '/': received 'true' but current is 'false'")
 
[2017-04-07 14:47:08]: 

[2017-04-07 14:47:08]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\spiders\ProcessDayUrlSpider.py", line 34, in parse
    for number in range(1, page_numer + 1, 1):
TypeError: coercing to Unicode: need string or buffer, int found
 coercing to Unicode: need string or buffer, int found
[2017-04-07 14:47:08]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\database\ServerHandler.py", line 25, in add_message
    channel.queue_declare(queue=queue, durable=queue_durable)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 2329, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 1181, in _flush_output
    raise exceptions.ChannelClosed(method.reply_code, method.reply_text)
ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue '2016_day_url_queue' in vhost '/': received 'true' but current is 'false'")
 
[2017-04-07 14:48:11]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\spiders\ProcessDayUrlSpider.py", line 35, in parse
    for number in range(1, page_numer + 1, 1):
TypeError: coercing to Unicode: need string or buffer, int found
 coercing to Unicode: need string or buffer, int found
[2017-04-07 14:48:11]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\database\ServerHandler.py", line 25, in add_message
    channel.queue_declare(queue=queue, durable=queue_durable)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 2329, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 1181, in _flush_output
    raise exceptions.ChannelClosed(method.reply_code, method.reply_text)
ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue '2016_day_url_queue' in vhost '/': received 'true' but current is 'false'")
 
[2017-04-07 14:48:40]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\spiders\ProcessDayUrlSpider.py", line 35, in parse
    for number in range(1, page_numer + 1, 1):
TypeError: coercing to Unicode: need string or buffer, int found
 coercing to Unicode: need string or buffer, int found
[2017-04-07 14:48:40]: 
Traceback (most recent call last):
  File "D:\Workspace\PyCharmProjects\xywy_ask_answer\database\ServerHandler.py", line 25, in add_message
    channel.queue_declare(queue=queue, durable=queue_durable)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 2329, in queue_declare
    self._flush_output(declare_ok_result.is_ready)
  File "D:\Program Files\Anaconda2\lib\site-packages\pika\adapters\blocking_connection.py", line 1181, in _flush_output
    raise exceptions.ChannelClosed(method.reply_code, method.reply_text)
ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'durable' for queue '2016_day_url_queue' in vhost '/': received 'true' but current is 'false'")
 
[2017-04-07 14:50:41]: 

[2017-04-07 14:50:56]: 

[2017-04-07 14:51:05]: 

[2017-04-07 14:53:24]: 

